@startuml

package "I. Modulo TRE: f)" {
class Eleitor {
nome
numTitulo
munEleitoral
zonaEleitoral
secaoEleitoral
}

class Candidatos {
nome
numeroCandidato
municipio
partido
cargo
}

class Urna {
municipio
zonaEleitoral
secaoEleitoral
}

Class Arquivo1 {
secaoEleitoral
numsTitulos
}

Class Arquivo2 {
zonaEleitoral
numeroCandidato
partido
cargo
}

Eleitor - Urna
(Eleitor, Urna) .. Arquivo1
(Candidatos, Urna) .. Arquivo2

}

@enduml